# Section with Qubership APIHUB Traffic Analyzer configuration
qubershipApihubTrafficAnalyzer:
  image:
    repository: 'ghcr.io/netcracker/qubership-apihub-traffic-analyzer' 
    tag: 'dev'
  # Section with resource limits
  # Mandatory
  # Below are the default values which are good enough for quick start, sandbox and over non production cases
  resource:
    memory:  
      request: "512Mi"
      limit: "512Mi"
    cpu:  
      request: "100m"
      limit: "1"
  # Optional; Set log level on init to specified value. Values: Info, Warn, Error, etc; If not set, default value: INFO; Example: DEBUG
  logLevel: "INFO"
  spec:
    replicas: 1
  # Mandatory; Qubserhip APIHUB Traffic Analyzer server URL for Ingress; Example: apihub-traffic-analyzer.example.com
  analyzerUrl: ''
  # Section with enviroment parameters for Qubership APIHUB Traffic Analyzer
  env:
    # Optional; Enables production mode; Example: TRUE
    productionMode: false
    # Mandatory; API key Qubserhip APIHUB Sniffer Agent public API access. Any string; Example: xyz
    snifferApiKey: ''
    # Optional; Allows to set extra allowed origin to CORS header. Used for FE debugging. Should be empty on prod evs.; If not set, default value: ""; Example: https://localhost:5137
    originAllowed: ''
    # Section with PostgreSQL database connection parameters
    database:
      # Mandatory; PostgreSQL database host ; Example: postgres.example.com
      dbHost: ''
      # Mandatory; PostgreSQL database port;  Example: 5432
      dbPort: ''
      # Mandatory; Logical database in PostgreSQL cluster for Qubership APIHUB Traffic Analyzer. Manual pre-creation required; Example: traffic_analyzer
      dbName: ''
      # Mandatory; User for Qubership APIHUB Traffic Analyzer dbName database; Example: traffic_analyzer
      dbUsername: ''
      # Mandatory; Password for dbUsername user; Example: traffic_analyzer
      dbPassword: ''
    # Section with APIHUB integration parameters
    qubershipApihub:
      # Mandatory; URL to integration with APIHUB UI; Example: http://apihub.example.com
      url: '' 
      # Mandatory; Access token for APIHUB integration; Example: xyz
      accessToken: ''
    # Section with S3 storage integration parameters.
    s3storage:
      # Mandatory; Access Key ID from S3 storage; Example: s3-access-key
      username: ''
      # Mandatory; Secret key for S3 storage access; Example: s3-secret-key
      password: ''
      # Mandatory; Certificate for accessing S3 storage; Example: LS0tLS1CRUdJTiBQUklWQV...
      crt: ''
      # Mandatory; S3 endpoint for client connection; Example: s3.example.com
      url: ''
      # Mandatory; Bucket name in S3 storage; Example: apihub-sniffer-s3-bucket
      bucketName: ''
      # Mandatory; Set to true to enable S3 integration. S3 is used for store temporary relatively large files.; Example: TRUE
      active: 'true'

