s3storage:
    username: ''
    password: ''
#   public.crt | base64
    crt: ''
    url: 'minio.minio-tenant'
    bucketName: 'qubership-apihub-sniffer-s3-bucket'
    active: 'true'



qubershipApihub:
  url: 'qubership-apihub-backend.qubership-apihub.svc.cluster.local' 
  accessToken: ''
  
qubershipApihubTrafficAnalyzer:
  apiKey: ''

  image:
    repository: 'ghcr.io/netcracker/qubership-apihub-traffic-analyzer' 
    tag: 'dev'

  resource:
    memory:  
      request: "512Mi"
      limit: "512Mi"
    cpu:  
      request: "100m"
      limit: "1"

  spec:
   replicas: 1

  env:
    monitoringEnabled: false
    insecureProxy: true
    originAllowed: ''
    logLevel: "DEBUG"
    productionMode: false
    database:
      dbHost: 'pg-common.postgres-db.svc.cluster.local'
      dbPort: '5432'
      dbName: ''
      dbUsername: ''
      dbPassword: ''

