apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: apihub-traffic-analyzer
    annotations:
        nginx.ingress.kubernetes.io/proxy-connect-timeout: '3600'
        nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
        nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
    labels:
        app.kubernetes.io/part-of: 'qubership-apihub-traffic-analyzer'
        app.kubernetes.io/managed-by: 'helm'

spec:
    ingressClassName: nginx
    rules:
        -   host: '{{ .Values.qubership-apihub-traffic-analyzer.analyzerUrl }}'
            http:
                paths:
                    -   path: /
                        pathType: ImplementationSpecific
                        backend:
                            service:
                                name: 'qubership-apihub-traffic-analyzer'
                                port:
                                    name: web
