---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: 'qubership-apihub-traffic-analyzer-view'
  labels:
    app.kubernetes.io/part-of: 'qubership-apihub-traffic-analyzer'
    app.kubernetes.io/managed-by: 'helm'
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: 'qubership-apihub-traffic-analyzer'
