apiVersion: v1
stringData:
  pg_user: '{{ .Values.qubershipApihubTrafficAnalyzer.env.database.dbUsername }}'
  pg_password: '{{ .Values.qubershipApihubTrafficAnalyzer.env.database.dbPassword }}'
kind: Secret
metadata:
  name: 'qubership-apihub-traffic-analyzer-db-secret'
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/part-of: 'qubership-apihub-traffic-analyzer'
    app.kubernetes.io/managed-by: 'helm'
type: Opaque

