---
apiVersion: v1
stringData:
  api_key: '{{ .Values.qubershipApihubTrafficAnalyzer.env.snifferApiKey }}'
  apihub_access_token: '{{ .Values.qubershipApihubTrafficAnalyzer.env.qubershipApihub.accessToken}}'
kind: Secret
metadata:
    name: 'qubership-apihub-traffic-analyzer-secret' 
    namespace: '{{ .Release.Namespace }}'
    annotations:
        kubernetes.io/service-account.name: 'qubership-apihub-traffic-analyzer'
    labels:
        app.kubernetes.io/part-of: 'qubership-apihub-traffic-analyzer'
        app.kubernetes.io/managed-by: 'helm'
type: kubernetes.io/service-account-token

