apiVersion: v1
stringData:
    storage_server_access_key_id: '{{ .Values.qubershipApihubTrafficAnalyzer.env.s3storage.username }}'
    storage_server_secret_access_key: '{{ .Values.qubershipApihubTrafficAnalyzer.env.s3storage.password }}'
    storage_server_crt: '{{ .Values.qubershipApihubTrafficAnalyzer.env.s3storage.crt }}'
    storage_server_endpoint: '{{ .Values.qubershipApihubTrafficAnalyzer.env.s3storage.url }}'
    storage_server_bucket_name: '{{ .Values.qubershipApihubTrafficAnalyzer.env.s3storage.bucketName }}'
kind: Secret
metadata:
    name: 'qubership-apihub-traffic-analyzer-s3storage-secret'
    namespace: '{{ .Release.Namespace }}'
    labels:
        app.kubernetes.io/part-of: 'qubership-apihub-traffic-analyzer'
        app.kubernetes.io/managed-by: 'helm'
type: Opaque