---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: 'qubership-apihub-traffic-analyzer'
    namespace: '{{ .Release.Namespace }}'
    labels:
        app.kubernetes.io/part-of: 'qubership-apihub-traffic-analyzer'
        app.kubernetes.io/managed-by: 'helm'
