name: build Docker image, run E2E BE tests, run E2E FE tests

on:
  push:
    branches:
      - "**"     
    tags:
      - '**'
  pull_request:
    paths-ignore:
      - 'docs/**'
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  packages: write

jobs:
  build-docker-image:
    uses: netcracker/qubership-apihub-ci/.github/workflows/docker-ci.yml@main
    with:
        name: qubership-apihub-traffic-analyzer
        file: Dockerfile
        context: ""
        platforms: linux/amd64
        labels: |
            maintainer=qubership
