# Copyright 2024-2025 NetCracker Technology Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

openapi: 3.0.0

info:
  version: 2.2.0-alpha.3
  title: 'Nudr_DataRepository API OpenAPI file'
  description: |
    Unified Data Repository Service.
    © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.

externalDocs:
  description: 3GPP TS 29.504 V17.2.0; 5G System; Unified Data Repository Services; Stage 3
  url: 'http://www.3gpp.org/ftp/Specs/archive/29_series/29.504/'

servers:
  - description: API root
    url: '{apiRoot}/nudr-dr/v2'
    variables:
      apiRoot:
        default: https://example.com

security:
  - {}
  - oAuth2ClientCredentials:
      - nudr-dr

paths:
  /subscription-data/{ueId}/authentication-data/authentication-subscription:
    $ref: 'paths_spec.yaml#/paths/~1subscription-data~1%7BueId%7D~1authentication-data~1authentication-subscription'

components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '{nrfApiRoot}/oauth2/token'
          scopes:
            nudr-dr: Access to the Nudr_DataRepository API
            nudr-dr:subscription-data: Access to the SubscriptionData data set
            nudr-dr:subscription-data:authentication-subscription:read: Access to read the AuthenticationSubscription resource of the SubscriptionData data set
            nudr-dr:subscription-data:authentication-subscription:modify: Access to update the AuthenticationSubscription resource of the SubscriptionData data set
            nudr-dr:subscription-data:registrations:write: Write access to NF registration resources of the SubscriptionData data set
            nudr-dr:policy-data: Access to the PolicyData data set
            nudr-dr:exposure-data: Access to the ExposureData data set
            nudr-dr:application-data: Access to the ApplicationData data set
