# Copyright 2024-2025 NetCracker Technology Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

openapi: 3.0.0
info:
  version: '-'
  title: 'Unified Data Repository Service API file for subscription data'
  description: |
    Unified Data Repository Service (subscription data).
    The API version is defined in 3GPP TS 29.504.
    © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.

externalDocs:
  description: 3GPP TS 29.505 V17.2.0; 5G System; Usage of the Unified Data Repository Service for subscription data; Stage 3
  url: 'http://www.3gpp.org/ftp/Specs/archive/29_series/29.505/'

paths:
  /subscription-data/{ueId}/authentication-data/authentication-subscription:
    get:
      summary: Retrieves the authentication subscription data of a UE
      operationId: QueryAuthSubsData
      tags:
        - Authentication Data (Document)
      security:
        - {}
        - oAuth2ClientCredentials:
          - nudr-dr
        - oAuth2ClientCredentials:
          - nudr-dr
          - nudr-dr:subscription-data:authentication-subscription:read
      parameters:
        - name: ueId
          in: path
          description: UE id
          required: true
        - name: supported-features
          in: query
          description: Supported Features
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
    patch:
      summary: modify the authentication subscription data of a UE
      operationId: ModifyAuthenticationSubscription
      tags:
        - Authentication Subscription (Document)
      security:
        - {}
        - oAuth2ClientCredentials:
          - nudr-dr
        - oAuth2ClientCredentials:
          - nudr-dr
          - nudr-dr:subscription-data:authentication-subscription:modify
      parameters:
        - name: ueId
          in: path
          description: UE id
          required: true
        - name: supported-features
          in: query
          description: Features required to be supported by the target NF
      requestBody:
        content:
          application/json-patch+json:
            schema:
              type: array
        required: true
      responses:
        '204':
          description: Expected response to a valid request
        '403':
          description: modification is rejected
          content:
            application/problem+json:

        '200':
          description: Expected response to a valid request
          content:
            application/json:

components:
  schemas:
    AuthenticationSubscription:
      type: object
      required:
        - authenticationMethod
      properties:
        authenticationMethod:
          $ref: '#/components/schemas/AuthMethod'
        encPermanentKey:
          type: string
        protectionParameterId:
          type: string
        sequenceNumber:
          $ref: '#/components/schemas/SequenceNumber'
        authenticationManagementField:
          type: string
          pattern: '^[A-Fa-f0-9]{4}$'
        algorithmId:
          type: string
        encOpcKey:
          type: string
        encTopcKey:
          type: string
        vectorGenerationInHss:
          type: boolean
          default: false
        n5gcAuthMethod:
          $ref: '#/components/schemas/AuthMethod'
        rgAuthenticationInd:
          type: boolean
          default: false
        akmaAllowed:
          type: boolean
          default: false

    SequenceNumber:
      type: object
      properties:
        sqnScheme:
          $ref: '#/components/schemas/SqnScheme'
        sqn:
          type: string
          pattern: '^[A-Fa-f0-9]{12}$'
        lastIndexes:
          type: object
          additionalProperties:
            type: integer
            minimum: 0
            description: A map(list of key-value pairs) where type of node serves as key
        indLength:
          type: integer
          minimum: 0
        difSign:
          $ref: '#/components/schemas/Sign'

    SqnScheme:
      anyOf:
        - type: string
          enum:
            - GENERAL
            - NON_TIME_BASED
            - TIME_BASED
        - type: string
    Sign:
      type: string
      enum:
        - POSITIVE
        - NEGATIVE
    VarPlmnId:
      type: string
      pattern: '^[0-9]{5,6}$'
    DatasetNames:
      type: array
      items:
        $ref: '#/components/schemas/DataSetName'
      minItems: 1
      uniqueItems: true
    DataSetName:
      anyOf:
      - type: string
        enum:
        - AM
        - SMF_SEL
        - SMS_SUB
        - SM
        - TRACE
        - SMS_MNG
        - LCS_PRIVACY
        - LCS_MO
        - LCS_BCA
        - V2X
      - type: string
    OperatorSpecificDataContainer:
      type: object
      required:
        - dataType
        - value
      properties:
        dataType:
          type: string
          enum:
            - string
            - integer
            - number
            - boolean
            - object
        dataTypeDefinition:
          type: string
        value:
          oneOf:
            - type: string
            - type: integer
            - type: number
            - type: boolean
            - type: object
    AuthMethod:
      anyOf:
        - type: string
          enum:
            - 5G_AKA
            - EAP_AKA_PRIME
            - EAP_TLS
        - type: string
